services:
  web:
    image: qingquanli/lost-and-found:latest
    container_name: lost-and-found # name the container
    ports:
      - "8001:80" # host:container
    depends_on:
      - db
    restart: always # always restart the container if it stops

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db_data:/var/lib/mysql
    restart: always # always restart the container if it stops

volumes:
  db_data: {}
